export const SET_USER_DATA = "SET_USER_DATA";
export const SET_CACHE_DATA = "SET_CACHE_DATA";
export const AFTER_SET_CACHE_DATA = "AFTER_SET_CACHE_DATA";
export const SET_NATIONALITY = "SET_NATIONALITY";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const UPDATE_PAGE_NUM = "UPDATE_PAGE_NUM";
export const SET_USER_SEARCH = "SET_USER_SEARCH";
